CREATE SEQUENCE MYNOSEQ
CREATE TABLE MYBOARD(
	MYNO NUMBER PRIMARY KEY,
	MYNAME VARCHAR2(100) NOT NULL,
	MYTITLE VARCHAR2(200) NOT NULL,
	MYCONTENT VARCHAR2(2000) NOT NULL,
	MYDATE DATE NOT NULL
)

SELECT * FROM MYBOARD

INSERT INTO MYBOARD VALUES(MYNOSEQ.NEXTVAL, '관리자', '제목', '내용', SYSDATE)

select * from user_sequences

SELECT MYNO, MYNAME, MYTITLE, MYCONTENT, MYDATE
FROM MYBOARD
ORDER BY MYNO DESC